--- #YAML:1.0
name: SQL-KeywordSearch
version: 1.11
author:
  - Mark Stosberg <mark@summersault.com>
abstract: generate SQL for simple keyword searches
license: perl
requires:
  Test::More: 0
recommends:
  SQL::Intepolate: 0
provides:
  SQL::KeywordSearch:
    file: lib/SQL/KeywordSearch.pm
    version: 1.11
generated_by: Module::Build version 0.2611
